"""
Django settings for CrazyPassword project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import django_heroku


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')
STATIC_DIR = os.path.join(BASE_DIR, 'static')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
with open('secret-key.txt') as f:
    SECRET_KEY = f.read().strip()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'https://crazypassword.herokuapp.com/']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'CrazyPasswordApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'CrazyPassword.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CrazyPassword.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
# Disable default validators    
#    {
#        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#    },
#    {
#        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#         'OPTIONS': {
#            'min_length': 10,
#        }
#    },
#    {
#        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#    },
#    {
#        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#    },

# Add custom validators from validators.py
    {'NAME': 'CrazyPasswordApp.validators.NumberValidator', },
    {'NAME': 'CrazyPasswordApp.validators.UppercaseValidator', },
    {'NAME': 'CrazyPasswordApp.validators.LowercaseValidator', },
    {'NAME': 'CrazyPasswordApp.validators.SymbolValidator', },
    {'NAME': 'CrazyPasswordApp.validators.MinLengthValidator', },
    {'NAME': 'CrazyPasswordApp.validators.AnotherLengthValidator', },
    {'NAME': 'CrazyPasswordApp.validators.MaxLengthValidator', },
    {'NAME': 'CrazyPasswordApp.validators.NoSpaceValidator', },
    {'NAME': 'CrazyPasswordApp.validators.UpperCountValidator', },
    {'NAME': 'CrazyPasswordApp.validators.LowerCountValidator', },
    {'NAME': 'CrazyPasswordApp.validators.NoEValidator', },
    {'NAME': 'CrazyPasswordApp.validators.NoSValidator', },
    {'NAME': 'CrazyPasswordApp.validators.IdenticalNumbersValidator', },
    {'NAME': 'CrazyPasswordApp.validators.RangeCountValidator', },
    {'NAME': 'CrazyPasswordApp.validators.GreekLetterValidator', },
    {'NAME': 'CrazyPasswordApp.validators.CapitalNeighborValidator', },
    {'NAME': 'CrazyPasswordApp.validators.SumNumbersValidator', },
    {'NAME': 'CrazyPasswordApp.validators.YearValidator', },
    {'NAME': 'CrazyPasswordApp.validators.UpperCountValidator', },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Activate Django-Heroku.
django_heroku.settings(locals())

